# Generated by Django 6.0.2 on 2026-02-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
